#!/usr/bin/env bash

set -euo pipefail

PYTHONPATH_VALUE="${PYTHONPATH_VALUE:-agent:emulator}"
UVICORN_BIN="${UVICORN_BIN:-.venv/bin/uvicorn}"
DB_PATH="${DB_PATH:-.data/simple-agent.sqlite3}"
AGENT_EMAIL_VALUE="${AGENT_EMAIL_VALUE:-agent@example.com}"
TASK_TRACKER_MCP_URL_VALUE="${TASK_TRACKER_MCP_URL_VALUE:-http://127.0.0.1:8020/mcp}"
TASK_TRACKER_MCP_TIMEOUT_SECONDS_VALUE="${TASK_TRACKER_MCP_TIMEOUT_SECONDS_VALUE:-30}"
PROJECT_REPO_ROOT_VALUE="${PROJECT_REPO_ROOT_VALUE:-}"
WORKSPACE_ROOT_VALUE="${WORKSPACE_ROOT_VALUE:-.data/workspaces}"
TOOL_COMMAND_TIMEOUT_SECONDS_VALUE="${TOOL_COMMAND_TIMEOUT_SECONDS_VALUE:-10}"
TOOL_OUTPUT_MAX_BYTES_VALUE="${TOOL_OUTPUT_MAX_BYTES_VALUE:-32000}"
TOOL_FILE_READ_MAX_BYTES_VALUE="${TOOL_FILE_READ_MAX_BYTES_VALUE:-128000}"
AGENT_RUNTIME_MODE_VALUE="${AGENT_RUNTIME_MODE_VALUE:-primitive}"
LLM_BASE_URL_VALUE="${LLM_BASE_URL_VALUE:-}"
LLM_API_KEY_VALUE="${LLM_API_KEY_VALUE:-}"
LLM_MODEL_VALUE="${LLM_MODEL_VALUE:-openai/gpt-5-mini}"
LLM_MAX_STEPS_VALUE="${LLM_MAX_STEPS_VALUE:-6}"
LLM_TIMEOUT_SECONDS_VALUE="${LLM_TIMEOUT_SECONDS_VALUE:-60}"
BACKEND_HOST_VALUE="${BACKEND_HOST_VALUE:-127.0.0.1}"
BACKEND_PORT_VALUE="${BACKEND_PORT_VALUE:-8010}"
APP_ENV_VALUE="${APP_ENV_VALUE:-local}"

if [[ -n "${NO_PROXY_VALUE:-}" ]]; then
  export NO_PROXY="${NO_PROXY_VALUE}"
  export no_proxy="${NO_PROXY_VALUE}"
fi

export PYTHONPATH="${PYTHONPATH_VALUE}"
export APP_ENV="${APP_ENV_VALUE}"
export SIMPLE_AGENT_DB_PATH="${DB_PATH}"
export AGENT_EMAIL="${AGENT_EMAIL_VALUE}"
export TASK_TRACKER_MCP_URL="${TASK_TRACKER_MCP_URL_VALUE}"
export TASK_TRACKER_MCP_TIMEOUT_SECONDS="${TASK_TRACKER_MCP_TIMEOUT_SECONDS_VALUE}"
if [[ -n "${PROJECT_REPO_ROOT_VALUE}" ]]; then
  export PROJECT_REPO_ROOT="${PROJECT_REPO_ROOT_VALUE}"
fi
export WORKSPACE_ROOT="${WORKSPACE_ROOT_VALUE}"
export TOOL_COMMAND_TIMEOUT_SECONDS="${TOOL_COMMAND_TIMEOUT_SECONDS_VALUE}"
export TOOL_OUTPUT_MAX_BYTES="${TOOL_OUTPUT_MAX_BYTES_VALUE}"
export TOOL_FILE_READ_MAX_BYTES="${TOOL_FILE_READ_MAX_BYTES_VALUE}"
export AGENT_RUNTIME_MODE="${AGENT_RUNTIME_MODE_VALUE}"
export LLM_BASE_URL="${LLM_BASE_URL_VALUE}"
export LLM_API_KEY="${LLM_API_KEY_VALUE}"
export LLM_MODEL="${LLM_MODEL_VALUE}"
export LLM_MAX_STEPS="${LLM_MAX_STEPS_VALUE}"
export LLM_TIMEOUT_SECONDS="${LLM_TIMEOUT_SECONDS_VALUE}"

exec "${UVICORN_BIN}" simple_agent.service.asgi:app --reload --host "${BACKEND_HOST_VALUE}" --port "${BACKEND_PORT_VALUE}"
